#   _  __         _
# | |/ /        | |
# | ' / ___ _ __| |__
# |  < / _ \ '__| '_ \
# | . \  __/ |  | |_) |
# |_|\_\___|_|  |_.__/
#
# Author: Smuddgge

# The server's port.
port: 5000

# The path to the server certificate.
server_certificate_path: "server.p12"

# The path to the client certificate.
client_certificate_path: "client.p12"

# The password to log in to the server and
# also access the certificates.
password: "123"

# The amount of seconds the server should expect
# to validate the client within.
timeout: 5

# The number of seconds to wait between checking if
# the client is still connected.
is_still_connected_seconds: 60

# Weather IPs that are not in the list should be blocked.
block_other_connections: false

# The list of names for ip addresses.
names:
  "/ip_with_dashes:port": "Computer"
  "/ip2_with_dashes:port": "Server 1"