#   _  __         _
# | |/ /        | |
# | ' / ___ _ __| |__
# |  < / _ \ '__| '_ \
# | . \  __/ |  | |_) |
# |_|\_\___|_|  |_.__/
#
# Event distributor server software.
# Author: Smuddgge

# The port the server is running on.
port: 7000

# The path to the server certificate
# and client certificate.
server_certificate_path: "server.p12"
client_certificate_path: "client.p12"

# The password that is used to access the
# certificates.
# This password will also be used to
# log in to the server.
password: "123"

# The amount of seconds the server should expect
# to validate the client within.
timeout: 5

# The number of milliseconds to wait for a
# server event to be sent back.
# If clients are getting disconnected randomly, this may
# need to be increased to give clients more time to respond.
max_wait_time_mills: 500

# The number of seconds to wait between checking if
# the client is still connected.
is_still_connected_seconds: 60

# When set to true, the server will kick old
# connections with the same name as a new connection.
kick_duplicate_names: false

# When set to true, IPs that are not in the list
# will be kicked.
block_other_connections: false

# Here you can assign names to IP addresses.
# Instead of using dots in the IP address,
# you should use underscores as the yaml parser
# sees dots as the path splitter.
names:
  "ip1-with-dashes:?": "Known Source"
  "ip2-with-dashes:port": "Server 1"
